Fix error reports from proxy runs

diff --git a/plugins/brdexec_proxy b/plugins/brdexec_proxy
--- a/plugins/brdexec_proxy
+++ b/plugins/brdexec_proxy
@@ -119,10 +119,6 @@ brdexec_proxy__brdexec_before_ssh () {
       BRDEXEC_SELECTED_PARAMETERS_INFO_PROXY="$(echo "${BRDEXEC_SELECTED_PARAMETERS_INFO}" | sed -e "s#/all.#/${BRDEXEC_PROXY_HOST_NAME}.#g")"
     fi
 
-#    echo "echo \"${BRDEXEC_PROXY_PATH}/broadexec.sh ${BRDEXEC_PARAMETERS_BACKUP_PROXY} ${BRDEXEC_SELECTED_PARAMETERS_INFO_PROXY} --external --runid ${RUNID} --batch -qq\" | ssh -p ${BRDEXEC_PROXY_PORT} -o StrictHostKeyChecking=yes -o BatchMode=yes${BRDEXEC_USER_SSH_KEY} -o \"ConnectTimeout=${BRDEXEC_SSH_CONNECTION_TIMEOUT}\" ${BRDEXEC_PROXY_USER}@${BRDEXEC_PROXY_HOST} \"cat > /tmp/${BRDEXEC_RUNID}_external.sh && chmod +x /tmp/${BRDEXEC_RUNID}_external.sh && /tmp/${BRDEXEC_RUNID}_external.sh; rm /tmp/${BRDEXEC_RUNID}_external.sh\" 2>>${BRDEXEC_PROXY_ERROR_OUTPUT} >> ${BRDEXEC_PROXY_MAIN_OUTPUT} &"
-#exit
-#    echo "${BRDEXEC_PROXY_PATH}/broadexec.sh ${BRDEXEC_PARAMETERS_BACKUP_PROXY} ${BRDEXEC_SELECTED_PARAMETERS_INFO_PROXY} --external --runid ${RUNID} --batch -qq" | ssh -p ${BRDEXEC_PROXY_PORT} -o StrictHostKeyChecking=yes -o BatchMode=yes${BRDEXEC_USER_SSH_KEY} -o "ConnectTimeout=${BRDEXEC_SSH_CONNECTION_TIMEOUT}" ${BRDEXEC_PROXY_USER}@${BRDEXEC_PROXY_HOST} "cat > /tmp/${BRDEXEC_RUNID}_external.sh && chmod +x /tmp/${BRDEXEC_RUNID}_external.sh && /tmp/${BRDEXEC_RUNID}_external.sh; rm /tmp/${BRDEXEC_RUNID}_external.sh" 2>>${BRDEXEC_PROXY_ERROR_OUTPUT} >> ${BRDEXEC_PROXY_MAIN_OUTPUT} &
-
     unset BRDEXEC_PROXY_LIST_TO_BE_COPIED
     for PROXY_HOSTLIST_DIR in "${BRDEXEC_DEFAULT_HOSTS_FOLDER}" "${BRDEXEC_DEFAULT_HOSTS_FOLDER}/${BRDEXEC_TEAM_CONFIG}"; do
       for BRDEXEC_POSSIBLE_PROXY_ITEM in $(ls -1 "${PROXY_HOSTLIST_DIR}"); do
@@ -136,8 +132,6 @@ brdexec_proxy__brdexec_before_ssh () {
         break
       fi
     done
-
-#echo "HOSTLIST ${BRDEXEC_PROXY_LIST_TO_BE_COPIED}"
 
     BRDEXEC_TARDIR="$(mktemp /tmp/broadexec.XXXXXXXXXX)"
 
@@ -195,9 +189,7 @@ brdexec_proxy__brdexec_before_ssh () {
             --batch; \
       " 2>>${BRDEXEC_PROXY_ERROR_OUTPUT} >> ${BRDEXEC_PROXY_MAIN_OUTPUT} & 
     BRDEXEC_PROXY_PID="${!}"
-#echo "Proxy pid: ${BRDEXEC_PROXY_PID}"
     BRDEXEC_PROXY_PIDS+=" ${BRDEXEC_PROXY_PID}"
-#echo "PROXY initiated with PID $BRDEXEC_PROXY_PID"
     BRDEXEC_PROXY_MAIN_OUTPUT_ARRAY[$BRDEXEC_PROXY_PID]="${BRDEXEC_PROXY_MAIN_OUTPUT}"
     BRDEXEC_PROXY_ERROR_OUTPUT_ARRAY[$BRDEXEC_PROXY_PID]="${BRDEXEC_PROXY_ERROR_OUTPUT}"
     BRDEXEC_PROXY_TMP_STATS_FILE_ARRAY[$BRDEXEC_PROXY_PID]="${BRDEXEC_PROXY_TMP_STATS_FILE}"
@@ -206,109 +198,6 @@ brdexec_proxy__brdexec_before_ssh () {
     BRDEXEC_PROXY_PATH_ARRAY[$BRDEXEC_PROXY_PID]="${BRDEXEC_PROXY_PATH}"
     BRDEXEC_PROXY_PORT_ARRAY[$BRDEXEC_PROXY_PID]="${BRDEXEC_PROXY_PORT}"
   done
-
-#  ### loop through proxy instances and wait until they are finished
-#  BRDEXEC_START_TIME=$(date +%s)
-#  #local BRDEXEC_PROXY_DEATH_COUNTER="$(expr $(date +%s) - 900)" #FIXME set proper variable for timeout in config
-#  #BRDEXEC_PROXY_PID_TOTAL_COUNT="$(echo ${BRDEXEC_PROXY_PIDS}) | wc -w)"
-#  ### initial line of overall status
-#  echo "Total: gathering data..."
-#  while [ "${BRDEXEC_PROXY_DEATH_COUNTER}" -lt "${BRDEXEC_START_TIME}" ]; do
-#    local BRDEXEC_PROXY_DEATH_COUNTER="$(expr $(date +%s) - 900)" #FIXME set proper variable for timeout in config
-#
-#    ### get total progress data
-#    if [ ! -z "${BRDEXEC_CURRENT_STATS_FILE_NUM_TOTAL_SUM}" ]; then
-#      tput cuu1
-#
-#      tput el
-#      echo "Total: ${BRDEXEC_CURRENT_STATS_FILE_NUM_DONE_SUM}/${BRDEXEC_CURRENT_STATS_FILE_NUM_TOTAL_SUM}"
-#
-#      #reset values
-#      BRDEXEC_CURRENT_STATS_FILE_NUM_DONE_SUM=0
-#      BRDEXEC_CURRENT_STATS_FILE_NUM_TOTAL_SUM=0
-#
-#    fi
-#
-#    BRDEXEC_PROXY_PID_TOTAL_COUNT="$(echo ${BRDEXEC_PROXY_PIDS} | wc -w)"
-#    BRDEXEC_PROXY_PID_TOTAL_FINISHED=0
-#    for BRDEXEC_PROXY_PID in ${BRDEXEC_PROXY_PIDS}; do
-#      if [ "${BRDEXEC_PROXY_ALREADY_FINISHED_ARRAY[$BRDEXEC_PROXY_PID]}" = "yes" ]; then
-#        ((BRDEXEC_PROXY_PID_TOTAL_FINISHED++))
-#      fi
-#
-#      ### display progress
-##echo "STATSFILE ${BRDEXEC_PROXY_STATS_FILE_ARRAY[$BRDEXEC_PROXY_PID]}"
-##cat ${BRDEXEC_PROXY_MAIN_OUTPUT_ARRAY[$BRDEXEC_PROXY_PID]}
-##ls -la ${BRDEXEC_PROXY_MAIN_OUTPUT_ARRAY[$BRDEXEC_PROXY_PID]}
-#
-#      if [ -z "${BRDEXEC_PROXY_STATS_FILE_ARRAY[$BRDEXEC_PROXY_PID]}" ]; then
-#        if [ -f "${BRDEXEC_PROXY_MAIN_OUTPUT_ARRAY[$BRDEXEC_PROXY_PID]}" ]; then
-#          BRDEXEC_PROXY_STATS_FILE_ARRAY[$BRDEXEC_PROXY_PID]="$(cat ${BRDEXEC_PROXY_MAIN_OUTPUT_ARRAY[$BRDEXEC_PROXY_PID]} | head -n 1)"
-#
-##echo "====="
-##echo "$(cat ${BRDEXEC_PROXY_MAIN_OUTPUT_ARRAY[$BRDEXEC_PROXY_PID]})"
-#        fi
-##echo "MAIN_OUT: ${BRDEXEC_PROXY_MAIN_OUTPUT_ARRAY[$BRDEXEC_PROXY_PID]}"
-##cat ${BRDEXEC_PROXY_MAIN_OUTPUT_ARRAY[$BRDEXEC_PROXY_PID]}
-##echo "::: ${BRDEXEC_PROXY_STATS_FILE_ARRAY[$BRDEXEC_PROXY_PID]}"
-##echo "ERROR ${BRDEXEC_PROXY_ERROR_OUTPUT_ARRAY[$BRDEXEC_PROXY_PID]}"
-##cat ${BRDEXEC_PROXY_ERROR_OUTPUT_ARRAY[$BRDEXEC_PROXY_PID]}
-#      fi
-#
-#      unset BRDEXEC_CURRENT_STATS_FILE
-#      unset BRDEXEC_CURRENT_STATS_FILE_PROGRESS
-#      unset BRDEXEC_CURRENT_STATS_FILE_STATE
-#      unset BRDEXEC_CURRENT_STATS_FILE_ERROR
-#      unset BRDEXEC_CURRENT_STATS_FILE_NUM_DONE
-#      unset BRDEXEC_CURRENT_STATS_FILE_NUM_TOTAL
-#      if [ ! -z "${BRDEXEC_PROXY_TMP_STATS_FILE_ARRAY[$BRDEXEC_PROXY_PID]}" ]; then
-#
-##echo "STATS file, ${BRDEXEC_PROXY_PORT_ARRAY[$BRDEXEC_PROXY_PID]}, ${BRDEXEC_USER_SSH_KEY}, ${BRDEXEC_SSH_CONNECTION_TIMEOUT}, ${BRDEXEC_PROXY_USER_ARRAY[$BRDEXEC_PROXY_PID]}, ${BRDEXEC_PROXY_HOSTNAME_ARRAY[$BRDEXEC_PROXY_PID]}, ${BRDEXEC_PROXY_PATH_ARRAY[$BRDEXEC_PROXY_PID]}, ${BRDEXEC_PROXY_STATS_FILE_ARRAY[$BRDEXEC_PROXY_PID]}"
-##echo "ssh -p ${BRDEXEC_PROXY_PORT_ARRAY[$BRDEXEC_PROXY_PID]} -o StrictHostKeyChecking=yes -o BatchMode=yes${BRDEXEC_USER_SSH_KEY} -o \"ConnectTimeout=${BRDEXEC_SSH_CONNECTION_TIMEOUT}\" ${BRDEXEC_PROXY_USER_ARRAY[$BRDEXEC_PROXY_PID]}@${BRDEXEC_PROXY_HOSTNAME_ARRAY[$BRDEXEC_PROXY_PID]} \"cat ${BRDEXEC_PROXY_PATH_ARRAY[$BRDEXEC_PROXY_PID]}/${BRDEXEC_PROXY_STATS_FILE_ARRAY[$BRDEXEC_PROXY_PID]}\""
-#
-##        BRDEXEC_CURRENT_STATS_FILE="$(ssh -p ${BRDEXEC_PROXY_PORT_ARRAY[$BRDEXEC_PROXY_PID]} -o StrictHostKeyChecking=yes -o BatchMode=yes${BRDEXEC_USER_SSH_KEY} -o "ConnectTimeout=${BRDEXEC_SSH_CONNECTION_TIMEOUT}" ${BRDEXEC_PROXY_USER_ARRAY[$BRDEXEC_PROXY_PID]}@${BRDEXEC_PROXY_HOSTNAME_ARRAY[$BRDEXEC_PROXY_PID]} "cat ${BRDEXEC_PROXY_PATH_ARRAY[$BRDEXEC_PROXY_PID]}/${BRDEXEC_PROXY_STATS_FILE_ARRAY[$BRDEXEC_PROXY_PID]}" 2>/dev/null)"
-#        BRDEXEC_CURRENT_STATS_FILE+="$(egrep "^PROGRESS" ${BRDEXEC_PROXY_TMP_STATS_FILE_ARRAY[$BRDEXEC_PROXY_PID]} | tail -n 1)"
-#        BRDEXEC_CURRENT_STATS_FILE+="$(egrep "^STATE" ${BRDEXEC_PROXY_TMP_STATS_FILE_ARRAY[$BRDEXEC_PROXY_PID]} | tail -n 1)"
-#echo "ARRAY: ${BRDEXEC_PROXY_TMP_STATS_FILE_ARRAY[$BRDEXEC_PROXY_PID]}"
-#cat ${BRDEXEC_PROXY_TMP_STATS_FILE_ARRAY[$BRDEXEC_PROXY_PID]}
-#echo "OUT: ${BRDEXEC_CURRENT_STATS_FILE}"
-#        #if [ "${?}" -ne 0 ]; then
-##       #   tput el
-#        #  echo "${BRDEXEC_PROXY_HOSTNAME_ARRAY[$BRDEXEC_PROXY_PID]}: SSH error"
-#        #  BRDEXEC_CURRENT_STATS_FILE_ERROR="yes"
-#        #else
-#          BRDEXEC_CURRENT_STATS_FILE_PROGRESS="$(echo "${BRDEXEC_CURRENT_STATS_FILE}" | grep "^PROGRESS" | awk '{print $4}')"
-#          BRDEXEC_CURRENT_STATS_FILE_STATE="$(echo "${BRDEXEC_CURRENT_STATS_FILE}" | grep "^STATE" | awk '{print $2}')"
-#
-#          BRDEXEC_CURRENT_STATS_FILE_NUM_TOTAL="$(echo "${BRDEXEC_CURRENT_STATS_FILE}" | grep "^PROGRESS" | awk '{print $3}')"
-#          ((BRDEXEC_CURRENT_STATS_FILE_NUM_TOTAL_SUM+=BRDEXEC_CURRENT_STATS_FILE_NUM_TOTAL))
-#          BRDEXEC_CURRENT_STATS_FILE_NUM_DONE="$(echo "${BRDEXEC_CURRENT_STATS_FILE}" | grep "^PROGRESS" | awk '{print $2}')"
-#          if [ "${BRDEXEC_CURRENT_STATS_FILE_STATE}" = "FINISHED" ]; then
-#            BRDEXEC_CURRENT_STATS_FILE_NUM_DONE="${BRDEXEC_CURRENT_STATS_FILE_NUM_TOTAL}"
-#          fi
-#          ((BRDEXEC_CURRENT_STATS_FILE_NUM_DONE_SUM+=BRDEXEC_CURRENT_STATS_FILE_NUM_DONE))
-#      #if [ "$(echo "$BRDEXEC_CURRENT_STATS_FILE" | grep -c "^ssh:")" -gt 0 ]; then
-#      #  echo "${BRDEXEC_PROXY_HOSTNAME_ARRAY[$BRDEXEC_PROXY_PID]}: SSH error"
-#      #else
-#          tput el
-#          echo "${BRDEXEC_PROXY_HOSTNAME_ARRAY[$BRDEXEC_PROXY_PID]}: ${BRDEXEC_CURRENT_STATS_FILE_PROGRESS}"
-#        #fi
-#      else
-#        tput el
-#        echo "${BRDEXEC_PROXY_HOSTNAME_ARRAY[$BRDEXEC_PROXY_PID]}: no data received"
-#      fi
-#
-#    done
-#
-#    ### reset display position
-#    for useless_counter in $(seq $BRDEXEC_PROXY_PID_TOTAL_COUNT); do
-#      tput cuu1
-##echo >/dev/null
-#    done
-#
-#    ### easing demand for CPU in compatible way
-#    sleep 0.2 2>/dev/null || sleep 1
-#  done
 }
 
 brdexec_proxy__brdexec_display_output_until_timeout () {
@@ -321,19 +210,9 @@ brdexec_proxy__brdexec_display_output_until_timeout () {
       for BRDEXEC_PROXY_PID in ${BRDEXEC_PROXY_PIDS}; do
         sleep 0.1 2>/dev/null || sleep 1
         ps -p ${BRDEXEC_PROXY_PID} >/dev/null
-        if [ "$?" -ne 0 ]; then #&& [ -z "${BRDEXEC_CURRENT_STATS_FILE_STATE}" ]; then
-          #BRDEXEC_CURRENT_STATS_FILE_STATE="PROXY_ERROR"
+        if [ "$?" -ne 0 ]; then
           ((BRDEXEC_PROXY_RUN_FINISHED++))
         fi
-        #if [ "${BRDEXEC_CURRENT_STATS_FILE_STATE}" = "FINISHED" ] || [ "${BRDEXEC_CURRENT_STATS_FILE_STATE}" = "INTERRUPTED" ] || [ "${BRDEXEC_CURRENT_STATS_FILE_STATE}" = "PROXY_ERROR" ] || [ "${BRDEXEC_CURRENT_STATS_FILE_ERROR}" = "yes" ]; then
-        #((BRDEXEC_PROXY_RUN_FINISHED++))
-        #if [ "${BRDEXEC_PROXY_ALREADY_FINISHED_ARRAY[$BRDEXEC_PROXY_PID]}" != "yes" ]; then
-          #ps -p ${BRDEXEC_PROXY_PID} >/dev/null
-          #if [ "$?" -ne 0 ]; then
-          #  BRDEXEC_PROXY_ALREADY_FINISHED_ARRAY[$BRDEXEC_PROXY_PID]="yes"
-          #fi
-        #fi
-        #fi
       done
     done
 }
@@ -341,41 +220,34 @@ brdexec_proxy__brdexec_display_output_until_timeout () {
 brdexec_proxy__brdexec_display_main_output () {
 
   for BRDEXEC_PROXY_PID in ${BRDEXEC_PROXY_PIDS}; do
-#    unset BRDEXEC_PROXY_OUTPUT_REPORT
-#    BRDEXEC_PROXY_OUTPUT_REPORT="$(cat ${BRDEXEC_PROXY_MAIN_OUTPUT_ARRAY[$BRDEXEC_PROXY_PID]} | grep "^REPORT_FILE" | awk '{print $2}')"
-##echo "OUT $BRDEXEC_PROXY_OUTPUT_REPORT ${BRDEXEC_PROXY_MAIN_OUTPUT_ARRAY[$BRDEXEC_PROXY_PID]}"
-#    if [ ! -z "${BRDEXEC_PROXY_OUTPUT_REPORT}" ]; then
-#      # i know, genius var name :/
-#      BRDEXEC_PROXY_OUTPUT_REPORT_OUTPUT="$(ssh -p ${BRDEXEC_PROXY_PORT_ARRAY[$BRDEXEC_PROXY_PID]} -o StrictHostKeyChecking=yes -o BatchMode=yes${BRDEXEC_USER_SSH_KEY} -o "ConnectTimeout=${BRDEXEC_SSH_CONNECTION_TIMEOUT}" ${BRDEXEC_PROXY_USER_ARRAY[$BRDEXEC_PROXY_PID]}@${BRDEXEC_PROXY_HOSTNAME_ARRAY[$BRDEXEC_PROXY_PID]} "cat ${BRDEXEC_PROXY_PATH_ARRAY[$BRDEXEC_PROXY_PID]}/${BRDEXEC_PROXY_OUTPUT_REPORT}" 2>/dev/null )"
-#      if [ "${?}" -eq 0 ]; then
-#        if [ ! -z "${BRDEXEC_PROXY_OUTPUT_REPORT_OUTPUT}" ]; then
-#          echo -e "${BRDEXEC_PROXY_OUTPUT_REPORT_OUTPUT}"
-#        fi
-#      fi
-#    fi
-
-#echo "PID $BRDEXEC_PROXY_PID"
-#    echo "${BRDEXEC_PROXY_MAIN_OUTPUT_ARRAY[$BRDEXEC_PROXY_PID]}"
-#echo ${BRDEXEC_PROXY_MAIN_OUTPUT_ARRAY[$BRDEXEC_PROXY_PID]}
-#ls -la ${BRDEXEC_PROXY_MAIN_OUTPUT_ARRAY[$BRDEXEC_PROXY_PID]}
-cat ${BRDEXEC_PROXY_MAIN_OUTPUT_ARRAY[$BRDEXEC_PROXY_PID]} >> ${BRDEXEC_REPORT_PATH}/broadexec_${BRDEXEC_REPORT_SCRIPT_NAME}_${BRDEXEC_RUNID}.report
-cat ${BRDEXEC_PROXY_MAIN_OUTPUT_ARRAY[$BRDEXEC_PROXY_PID]}
+    egrep -v "Report has been saved in|Error report has been saved in" ${BRDEXEC_PROXY_MAIN_OUTPUT_ARRAY[$BRDEXEC_PROXY_PID]} >> \
+      ${BRDEXEC_REPORT_PATH}/broadexec_${BRDEXEC_REPORT_SCRIPT_NAME}_${BRDEXEC_RUNID}.report
+    egrep -v "Report has been saved in|Error report has been saved in" ${BRDEXEC_PROXY_MAIN_OUTPUT_ARRAY[$BRDEXEC_PROXY_PID]}
   done
 }
 
 brdexec_proxy__brdexec_generate_error_log () {
 
-  for BRDEXEC_PROXY_PID in ${BRDEXEC_PROXY_PIDS}; do
-    unset BRDEXEC_PROXY_ERROR_REPORT
-    BRDEXEC_PROXY_ERROR_REPORT="$(cat ${BRDEXEC_PROXY_MAIN_OUTPUT_ARRAY[$BRDEXEC_PROXY_PID]} | grep "^REPORT_ERROR" | awk '{print $2}')"
-    if [ ! -z "${BRDEXEC_PROXY_ERROR_REPORT}" ]; then
-      BRDEXEC_PROXY_ERROR_REPORT_OUTPUT="$(ssh -p ${BRDEXEC_PROXY_PORT_ARRAY[$BRDEXEC_PROXY_PID]} -o StrictHostKeyChecking=yes -o BatchMode=yes${BRDEXEC_USER_SSH_KEY} -o "ConnectTimeout=${BRDEXEC_SSH_CONNECTION_TIMEOUT}" ${BRDEXEC_PROXY_USER_ARRAY[$BRDEXEC_PROXY_PID]}@${BRDEXEC_PROXY_HOSTNAME_ARRAY[$BRDEXEC_PROXY_PID]} "cat ${BRDEXEC_PROXY_PATH_ARRAY[$BRDEXEC_PROXY_PID]}/${BRDEXEC_PROXY_ERROR_REPORT}" 2>/dev/null )"
-      if [ "${?}" -eq 0 ]; then
-        if [ ! -z "${BRDEXEC_PROXY_ERROR_REPORT_OUTPUT}" ]; then
-          echo "${BRDEXEC_PROXY_ERROR_REPORT_OUTPUT}" >> ${BRDEXEC_REPORT_ERROR_FILE}
-          echo "${BRDEXEC_PROXY_ERROR_REPORT_OUTPUT}" >> ${BRDEXEC_MAIN_ERROR_CURLOG}
+  #FIXME somewhat duplicate code from core brdexec_generate_error_log function :/
+  if [ -f "${BRDEXEC_ERROR_BLACKLIST_FILE}" ]; then
+    if [ "$(cat "${BRDEXEC_ERROR_BLACKLIST_FILE}" | wc -l)" -ne 0 ]; then
+      while read BRDEXEC_ERROR_BLACKLIST_LINE; do
+        if [ "$(echo "${BRDEXEC_ERROR_BLACKLIST_LINE}" | grep -c '^#')" -eq 0 ]; then
+          for BRDEXEC_PROXY_PID in ${BRDEXEC_PROXY_PIDS}; do
+            if [ "$(cat ${BRDEXEC_PROXY_ERROR_OUTPUT_ARRAY[$BRDEXEC_PROXY_PID]} | wc -l)" -gt 1 ] && \
+               [ "$(grep -c "${BRDEXEC_ERROR_BLACKLIST_LINE}" ${BRDEXEC_PROXY_ERROR_OUTPUT_ARRAY[$BRDEXEC_PROXY_PID]})" -gt 0 ]; then
+              BRDEXEC_ERROR_BLACKLIST_TEMP="$(mktemp /tmp/broadexec.XXXXXXXXXX)"
+              BRDEXEC_TEMP_FILES_LIST+=" ${BRDEXEC_ERROR_BLACKLIST_TEMP}"
+              grep -v "${BRDEXEC_ERROR_BLACKLIST_LINE}" ${BRDEXEC_PROXY_ERROR_OUTPUT_ARRAY[$BRDEXEC_PROXY_PID]} >> ${BRDEXEC_ERROR_BLACKLIST_TEMP} && mv ${BRDEXEC_ERROR_BLACKLIST_TEMP} ${BRDEXEC_PROXY_ERROR_OUTPUT_ARRAY[$BRDEXEC_PROXY_PID]}
+            fi
+          done
         fi
-      fi
+      done < ${BRDEXEC_ERROR_BLACKLIST_FILE}
     fi
+  fi
+
+  for BRDEXEC_PROXY_PID in ${BRDEXEC_PROXY_PIDS}; do
+    cat ${BRDEXEC_PROXY_ERROR_OUTPUT_ARRAY[$BRDEXEC_PROXY_PID]} >> ${BRDEXEC_MAIN_ERROR_CURLOG}
+    cat ${BRDEXEC_PROXY_ERROR_OUTPUT_ARRAY[$BRDEXEC_PROXY_PID]} >> ${BRDEXEC_REPORT_ERROR_FILE}
   done
 }
